spring.application.name=media-hub-backend

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=0123456789012345678901234567890123456789012345678901234567890123
jwt.expiration-minutes=60

server.port=8080