CREATE TABLE user_profile (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                              first_name VARCHAR(255),
                              last_name VARCHAR(255),
                              address VARCHAR(255),
                              profile_img_url VARCHAR(255)
);

CREATE TABLE app_user (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                          username VARCHAR(255) NOT NULL UNIQUE,
                          password_hash VARCHAR(255) NOT NULL,
                          role VARCHAR(50) NOT NULL,

                          profile_id BIGINT,

                          CONSTRAINT fk_app_user_profile
                              FOREIGN KEY (profile_id)
                                  REFERENCES user_profile(id)
);


CREATE UNIQUE INDEX IF NOT EXISTS idx_app_user_username ON app_user(username);


CREATE TABLE media
(
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,

    filename    VARCHAR(255),
    type        VARCHAR(255),
    visibility  BOOLEAN NOT NULL,

    title       VARCHAR(255),
    description VARCHAR(1000),

    version     BIGINT,

    owner_id    BIGINT,

    CONSTRAINT fk_media_owner
        FOREIGN KEY (owner_id)
            REFERENCES app_user (id)
);

CREATE INDEX IF NOT EXISTS idx_media_owner
    ON media(owner_id);

CREATE INDEX IF NOT EXISTS idx_media_filename
    ON media(filename);
